
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test2?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&useSSL=false
    username: root
    password: 63692234
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database: mysql
server:
  port: 8080

